<a href="https://colab.research.google.com/github/Luzinsan/PyCourseLuzinsan/blob/main/Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Задания

**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [ ]:
from math import sqrt

def distance(x1, y1, x2, y2):
  return sqrt(pow((x2-x1), 2) + pow((y2-y1), 2))


x1, y1, x2, y2 = [float(input()) for i in range(4)]
print(distance(x1, y1, x2, y2))

3
7
3
9
2.0


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [ ]:
s = 1

def season(month):
  global s
  if month<=2 or month==12:
    s = 'зима'
  elif month<=5:
    s = 'весна'
  elif month<=8:
    s = 'лето'
  else:
    s = 'осень'

season(int(input()))
print(s)

11
осень


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [ ]:
def is_prime(number: int):
  if number==0:
    return None
  for i in range(2, int(sqrt(number))):
    if number % i == 0:
      return False
  return True

for i in range(5):
  print(f"{i} is prime: {is_prime(i)}")  
print(is_prime(int(input())))

**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [ ]:
def referense_list(lst: list):
  return lst[::-1]

print(referense_list(input().split(', ')))

8, 1, 0, 4
['4', '0', '1', '8']


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [ ]:
hello_world = 'Привет мир!'
strip_world = hello_world[4:9].upper()
print(strip_world)

ЕТ МИ


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [ ]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x[1::2] = x[-1::-2]
print(x)

[0, 9, 2, 7, 4, 5, 6, 3, 8, 1]


**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [ ]:
[i for i in range(500) if i%7==0 and str(i).find('8')!=-1]

[28, 84, 98, 168, 182, 189, 238, 280, 287, 308, 378, 385, 448, 483]

**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [ ]:
def more_than_five(lst: list):
  return [i for i in lst if abs(i)>10]

lst = [1,5,0,-1,4,-14,29,-204]
print(more_than_five(lst))

[-14, 29, -204]


# Задания

In [ ]:
import numpy as np
from random import randint

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [ ]:
size = 10
task1 = np.zeros((size,size))
mask = np.full_like(task1, True, dtype=bool)
mask[1:-1, 1:-1] = False
task1[mask] = 1.
task1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [ ]:
task2 = np.diag(np.arange(1,5), k=1)
task2

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [ ]:
rng = np.random.default_rng()

**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [ ]:
task3 = rng.integers(1,10,(3,3))
print(task3, f'mean (axis=all) = {task3.mean()}', sep='\n')
task3 = task3 - task3.mean()
task3

[[2 4 7]
 [1 5 4]
 [6 9 8]]
mean (axis=all) = 5.111111111111111


array([[-3.11111111, -1.11111111,  1.88888889],
       [-4.11111111, -0.11111111, -1.11111111],
       [ 0.88888889,  3.88888889,  2.88888889]])

**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [ ]:
def reflect(matrix, value_from, value_to):
  matrix[np.logical_and(matrix > value_from, matrix < value_to)] *= -1
  return matrix

In [ ]:
probe = 5
value_from, value_to = 3, 8
for i in range(probe):
  task4 = rng.integers(1,10,(3,3))
  print(task4)
  print(f'reflected \
          \n\r{reflect(task4,value_from, value_to)}\n')

[[8 2 2]
 [5 5 4]
 [1 3 6]]
reflected           
[[ 8  2  2]
 [-5 -5 -4]
 [ 1  3 -6]]

[[5 8 5]
 [4 3 6]
 [7 6 1]]
reflected           
[[-5  8 -5]
 [-4  3 -6]
 [-7 -6  1]]

[[6 8 6]
 [5 7 4]
 [4 6 2]]
reflected           
[[-6  8 -6]
 [-5 -7 -4]
 [-4 -6  2]]

[[4 6 4]
 [4 5 5]
 [8 5 8]]
reflected           
[[-4 -6 -4]
 [-4 -5 -5]
 [ 8 -5  8]]

[[4 6 6]
 [8 2 6]
 [4 4 3]]
reflected           
[[-4 -6 -6]
 [ 8  2 -6]
 [-4 -4  3]]



**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

In [ ]:
def sub_mean(matrix):
  return np.array([matrix[i]-matrix.mean(axis=1)[i] for i in range(matrix.shape[0])])

In [ ]:
probe = 5
for i in range(probe):
  task4_2 = rng.integers(1,10,(3,3))
  print(task4_2, f'mean (axis=1) = {task4_2.mean(axis=1)}', sep='\n')
  print(f'converted \
          \n\r{sub_mean(task4_2)}\n')

[[3 1 8]
 [1 3 9]
 [7 3 6]]
mean (axis=1) = [4.         4.33333333 5.33333333]
converted           
[[-1.         -3.          4.        ]
 [-3.33333333 -1.33333333  4.66666667]
 [ 1.66666667 -2.33333333  0.66666667]]

[[2 6 3]
 [4 3 1]
 [7 5 7]]
mean (axis=1) = [3.66666667 2.66666667 6.33333333]
converted           
[[-1.66666667  2.33333333 -0.66666667]
 [ 1.33333333  0.33333333 -1.66666667]
 [ 0.66666667 -1.33333333  0.66666667]]

[[6 9 2]
 [4 9 9]
 [4 5 8]]
mean (axis=1) = [5.66666667 7.33333333 5.66666667]
converted           
[[ 0.33333333  3.33333333 -3.66666667]
 [-3.33333333  1.66666667  1.66666667]
 [-1.66666667 -0.66666667  2.33333333]]

[[1 3 4]
 [5 4 1]
 [7 7 1]]
mean (axis=1) = [2.66666667 3.33333333 5.        ]
converted           
[[-1.66666667  0.33333333  1.33333333]
 [ 1.66666667  0.66666667 -2.33333333]
 [ 2.          2.         -4.        ]]

[[7 9 5]
 [4 9 9]
 [6 3 4]]
mean (axis=1) = [7.         7.33333333 4.33333333]
converted           
[[ 0.          2.       

**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [ ]:
def with_zeros(vector, num_zeros):
  zeros_array = np.zeros(num_zeros, dtype=int)
  matrix_with_zeros = [np.concatenate([zeros_array, vector[i][np.newaxis]]) for i in range(1,vector.size)]
  edited_vector =np.concatenate([[1], np.array(matrix_with_zeros).flatten()])
  return edited_vector

task5 = np.array([1, 2, 3, 4, 5], dtype=int)
with_zeros(task5, 3)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [ ]:
def swap_rows(matrix, ind_row1, ind_row2):
  matrix[ind_row1], matrix[ind_row2] = matrix[ind_row2].copy(), matrix[ind_row1].copy()
  return matrix

In [ ]:
probe = 5
rows, columns = rng.integers(1,10,2)
print(f"shape=({rows}, {columns})")
for i in range(probe):
  task6 = rng.integers(1,10,(rows,columns))
  row1, row2 = rng.integers(0,rows,2)
  print(task6, f'row_1= {row1}\nrow_2= {row2}', sep='\n')
  print(f'swapped \
          \n\r{swap_rows(task6, row1, row2)}\n')

shape=(6, 9)
[[9 2 6 3 7 5 1 1 9]
 [6 9 6 2 3 3 4 8 8]
 [2 7 4 7 4 6 7 1 7]
 [8 8 3 1 4 3 4 6 4]
 [6 4 7 1 6 1 3 8 3]
 [4 6 1 1 8 9 2 4 9]]
row_1= 5
row_2= 4
swapped           
[[9 2 6 3 7 5 1 1 9]
 [6 9 6 2 3 3 4 8 8]
 [2 7 4 7 4 6 7 1 7]
 [8 8 3 1 4 3 4 6 4]
 [4 6 1 1 8 9 2 4 9]
 [6 4 7 1 6 1 3 8 3]]

[[6 3 6 2 9 3 8 5 6]
 [1 2 4 7 8 6 1 9 1]
 [4 5 7 4 4 5 5 3 8]
 [8 8 2 3 2 3 8 7 6]
 [8 4 1 9 2 9 1 1 1]
 [4 7 2 5 3 3 9 9 7]]
row_1= 2
row_2= 3
swapped           
[[6 3 6 2 9 3 8 5 6]
 [1 2 4 7 8 6 1 9 1]
 [8 8 2 3 2 3 8 7 6]
 [4 5 7 4 4 5 5 3 8]
 [8 4 1 9 2 9 1 1 1]
 [4 7 2 5 3 3 9 9 7]]

[[7 4 6 7 4 6 1 2 2]
 [4 3 6 9 2 6 6 4 6]
 [7 1 2 7 7 4 7 7 4]
 [3 1 7 9 5 1 1 3 5]
 [7 3 6 5 7 6 7 3 1]
 [4 5 1 3 5 8 8 5 6]]
row_1= 5
row_2= 2
swapped           
[[7 4 6 7 4 6 1 2 2]
 [4 3 6 9 2 6 6 4 6]
 [4 5 1 3 5 8 8 5 6]
 [3 1 7 9 5 1 1 3 5]
 [7 3 6 5 7 6 7 3 1]
 [7 1 2 7 7 4 7 7 4]]

[[7 4 3 1 3 4 7 9 9]
 [4 7 4 5 6 3 4 6 9]
 [1 1 5 6 6 9 5 2 9]
 [1 2 4 3 2 1 4 5 6]
 [3 7 1 3 9 3 6 3 5]
 [4 9 

**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [ ]:
def max_frequency(matrix):
  unique, counts = np.unique(matrix, return_counts=True)
  print(unique, counts)
  return unique[counts.argmax()], counts.max()

In [ ]:
probe = 5
for i in range(probe):
  length = randint(2,30)
  task7 = rng.integers(1,10,length)
  print(task7, f'length= {length}', sep='\n')
  value, frequency=max_frequency(task7)
  print(f'value={value},frequency={frequency}\n')

[7 7 4 2 9 8 6 6 9 4 5 1 9 5 2 1 6 9 6 8 3 7]
length= 22
[1 2 3 4 5 6 7 8 9] [2 2 1 2 2 4 3 2 4]
value=6,frequency=4

[2 6 4 3 5 6 4 7 4 5 2 3 1 1 9 2 2 6]
length= 18
[1 2 3 4 5 6 7 9] [2 4 2 3 2 3 1 1]
value=2,frequency=4

[6 3 4 6 1 5 1 5 1 7 6 7 9 6 4 4 8 9 6 6 2 7 6 1 5 4 7 2 6 3]
length= 30
[1 2 3 4 5 6 7 8 9] [4 2 2 4 3 8 4 1 2]
value=6,frequency=8

[3 3 3 6 3 3 3 2 2 7 9 8 9 2 7 6 5 2 8 4 5 3 1 4 1 9 8 5 3 4]
length= 30
[1 2 3 4 5 6 7 8 9] [2 4 8 3 3 2 2 3 3]
value=3,frequency=8

[8 8 1 1 8 4 7 7]
length= 8
[1 4 7 8] [2 1 2 3]
value=8,frequency=3



**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [ ]:
def convolution(matrix, block_rows, block_columns):
  return np.array([[matrix[block_rows*row:(row+1)*block_rows, block*block_columns:(block+1)*block_columns].sum() \
          for block in range(block_rows)] \
          for row in range(block_columns)])

In [ ]:
rows, columns = 16, 16
block_rows, block_columns = 4, 4

probe = 1
for i in range(probe):
  task8 = rng.integers(0,2,(rows,columns))
  print(task8)
  print(f'convolution=\n{convolution(task8, block_rows, block_columns)}\n')

[[1 0 0 1 1 0 1 1 0 0 0 1 0 0 1 1]
 [1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 0]
 [1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 0]
 [0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1]
 [1 1 1 0 1 0 0 1 0 1 1 0 1 1 0 0]
 [0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1]
 [0 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0]
 [0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0]
 [1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0]
 [1 0 0 0 1 1 1 1 1 0 0 0 0 1 0 1]
 [0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1]
 [1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0]
 [1 1 1 1 1 0 0 1 1 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0]
 [1 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0]]
convolution=
[[ 9  9  9  6]
 [ 7 13 10  7]
 [ 5  9  8 10]
 [10  7  7  5]]



**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [ ]:
def max_values(matrix, number):
  list_values = matrix.flatten()
  list_values.sort()
  return list_values[-number:]

In [ ]:
probe = 1
for i in range(probe):
  task9 = rng.integers(0,10,(3,3))
  print(task9)
  n = int(input("Number of maximum values: "))
  print(f'{n} max values={max_values(task9, n)}\n')

[[2 8 5]
 [8 4 7]
 [1 8 9]]
Number of maximum values: 3
3 max values=[8 8 9]



**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [ ]:
def non_unique_rows(matrix):
  indices = [i for i in range(matrix.shape[0]) if len(np.unique(matrix[i])) != 1]
  return indices, matrix[indices]

In [ ]:
probe = 1
for i in range(probe):
  task10 = rng.integers(0,2,(10,3))
  print(task10)
  indices, rows = non_unique_rows(task10)
  print(f'not unique rows=\nindices={indices}\nrows=\n{rows}\n')

[[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [1 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 1]
 [0 1 0]]
not unique rows=
indices=[0, 1, 2, 3, 5, 6, 7, 9]
rows=
[[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [0 1 0]
 [0 1 0]]



**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [ ]:
def unique_rows(matrix):
  return np.unique(matrix, axis=0)

In [ ]:
probe = 1
for i in range(probe):
  task11 = rng.integers(0,2,(10,3))
  print(task11)
  print(f'unique rows=\n{unique_rows(task11)}\n')

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]]
unique rows=
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]



**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [ ]:
def distance(vec1, vec2):
  diff = vec2-vec1
  return np.sqrt(np.dot(diff,diff))

In [ ]:
probe = 3
for i in range(probe):
  vec1, vec2 = rng.integers(0,10,3), rng.integers(0,10,3)  
  print(f'vec1={vec1};\tvec2={vec2}\ndistance={distance(vec1,vec2)}\n')

vec1=[3 1 1];	vec2=[1 1 8]
distance=7.280109889280518

vec1=[6 0 1];	vec2=[2 9 0]
distance=9.899494936611665

vec1=[6 3 2];	vec2=[6 1 6]
distance=4.47213595499958



**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [ ]:
from numpy.linalg import norm
def cos_arr(vec1, vec2):
  return np.dot(vec1, vec2)/(norm(vec1) * norm(vec2))

In [ ]:
probe = 3
for i in range(probe):
  vec1, vec2 = rng.integers(0,10,3), rng.integers(0,10,3)  
  print(f'vec1={vec1};\tvec2={vec2}\ncos={cos_arr(vec1,vec2)}\n')

vec1=[2 5 8];	vec2=[8 0 2]
cos=0.4023963638622855

vec1=[2 3 0];	vec2=[3 8 0]
cos=0.9738412097417933

vec1=[0 5 3];	vec2=[5 3 6]
cos=0.6764340508948999



**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


In [ ]:
def round_from_zero(vector):
  return np.ceil(vector)

In [ ]:
probe = 3
for i in range(probe):
  task14 = rng.uniform(-10, 10, 10)  
  print(f'vector={task14}\nrounded={round_from_zero(task14)}\n')

vector=[ 9.98472097  2.64463862 -0.65996409 -1.5582992  -1.52836959 -4.28189464
  3.95161311  9.17696811  9.09506909  7.26503071]
rounded=[10.  3. -0. -1. -1. -4.  4. 10. 10.  8.]

vector=[ 4.84724431 -9.65795287 -6.38616166  3.03687485 -8.11598961  8.22032792
  4.19617271 -8.78148784  7.22529688 -5.1659069 ]
rounded=[ 5. -9. -6.  4. -8.  9.  5. -8.  8. -5.]

vector=[ 1.43514553 -5.42043783  8.07756877  2.59744728  0.65456408 -8.25574912
  7.18655941  9.75175622  2.57843909  0.22660125]
rounded=[ 2. -5.  9.  3.  1. -8.  8. 10.  3.  1.]



**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

In [ ]:
def combing(vec1, vec2):
  return np.unique(vec1[np.in1d(vec1, vec2)])
  # return np.intersect1d(vec1, vec2)

In [ ]:
probe = 3
n = 10
for i in range(probe):
  vec1, vec2 = rng.integers(0,10,n), rng.integers(0,10,n)  
  print(f'vec1={vec1};\tvec2={vec2}\ncombing={combing(vec1,vec2)}\n')

vec1=[1 6 9 5 1 5 4 7 6 9];	vec2=[5 5 9 4 3 1 0 7 7 6]
combing=[1 4 5 6 7 9]

vec1=[4 7 5 0 2 7 3 0 9 6];	vec2=[5 0 7 2 0 4 3 5 6 6]
combing=[0 2 3 4 5 6 7]

vec1=[0 0 2 9 9 6 9 0 5 0];	vec2=[3 0 8 0 8 4 0 8 8 5]
combing=[0 5]



**Задача 16.**

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [ ]:
def max_after_zero(vector):
  list_after_zero = [value for counter, value in enumerate(vector[1:]) if vector[counter]==0]
  print(list_after_zero)
  if list_after_zero:
    return max(list_after_zero)
  else:
     return 
  # return np.max(vector[1:][(vector==0)[:-1]])

In [ ]:
n = 10
vec2 = rng.integers(0,3,n)
print(vec2)
max_after_zero(vec2)

[2 2 2 2 1 2 0 0 2 2]
[0, 2]


2

**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```

In [ ]:
from numpy.linalg import norm

def max_norm_vector(matrix):
  norms = np.array([norm(row) for row in matrix])
  print(norms)
  return norms.max(), matrix[norms.argmax()]

In [ ]:
task17 = rng.integers(0,3,(5,3))
print(task17)
print(max_norm_vector(task17))

[[1 1 1]
 [0 0 2]
 [1 2 1]
 [0 2 0]
 [0 0 1]]
[1.73205081 2.         2.44948974 2.         1.        ]
(2.449489742783178, array([1, 2, 1]))
